version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
      # target: production

    env_file:
      - ./.env
    
    environment:
      - NODE_ENV=production
    command: npm run start

